# Generated by Django 4.0.5 on 2022-06-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='diary.group', verbose_name='Состоит в группе'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='diary.group', verbose_name='Курирует группу'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(related_name='teachers', to='diary.lesson', verbose_name='Ведет предметы'),
        ),
    ]
