# Generated by Django 4.0.5 on 2022-06-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('people', '0002_student_group_teacher_group_manager_teacher_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='diary.group', verbose_name='Состоит в группе'),
        ),
    ]
