# Generated by Django 4.0.5 on 2022-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='diary/static/img/default-user.png', upload_to='people/'),
        ),
    ]
