# Generated by Django 4.0.5 on 2022-06-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Список предметов',
            },
        ),
        migrations.CreateModel(
            name='RatingItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Статус оценки')),
            ],
            options={
                'verbose_name': 'Cтатус оценки',
                'verbose_name_plural': 'Список статусов оценок',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='Номер группы')),
                ('create_group', models.DateField(verbose_name='Дата создания группы')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('lessons', models.ManyToManyField(related_name='group', to='diary.lesson', verbose_name='Пары класса')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Список групп',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='Оценка')),
                ('created', models.DateField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.group', verbose_name='Наименование группы')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.lesson', verbose_name='Предмет')),
                ('score_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.ratingitemstatus', verbose_name='Статус оценки')),
                ('student', models.ForeignKey(limit_choices_to={'user_status': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='score_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Оценки',
                'unique_together': {('student', 'lesson', 'created')},
            },
        ),
    ]
