# Generated by Django 4.0.5 on 2022-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_status',
        ),
        migrations.DeleteModel(
            name='RatingItemStatus',
        ),
    ]
