# Generated by Django 4.0.5 on 2022-06-06 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0003_alter_score_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_status': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='score_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
