# Generated by Django 4.0.5 on 2022-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_score_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='create_group',
        ),
        migrations.AlterField(
            model_name='group',
            name='lessons',
            field=models.ManyToManyField(related_name='group', to='diary.lesson', verbose_name='Предметы группы'),
        ),
    ]
